Added Gonzo class
mbramson/business_doer pull request #9
Opened 2017-03-15 22:43 UTC by gonzzzzz

Added a class named "Gonzzzz" and a test for it!

2017-03-15 22:49 UTC, mbramson requested changes
Add the class under test

2017-03-15 22:49 UTC, mbramson commented on spec/business_spec.rb
> +end
Looks great, where's the class?

2017-03-16 00:07 UTC, gonzzzzz commented on spec/business_spec.rb
> +end
Whoops!  
Errr, I think I correctly added it now?

2017-03-16 00:07 UTC, closed without merging

2017-03-16 13:20 UTC, mbramson reviewed
Perfect!

2017-03-16 13:20 UTC, mbramson commented on business.rb
> +  end
Solid!